import psycopg2


connection = psycopg2.connect(
    database="db_name",
    user="username",
    password="password",
    host="host",
    port=5432
)
connection.set_isolation_level(psycopg2.extensions.ISOLATION_LEVEL_AUTOCOMMIT)
cursor = connection.cursor()
cursor.execute("""CREATE TABLE IF NOT EXISTS exchange_rates (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      currency VARCHAR(3) NOT NULL,
                      rate REAL NOT NULL,
                      date TIMESTAMP NOT NULL
                  )
""")
connection.commit()
